import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices, 
    // Module, PartialLangiumServices
} from 'langium';
import { RslGeneratedModule, RslGeneratedSharedModule } from './generated/module';
import { QualifiedNameProvider } from './rsl-naming';
import { RslScopeComputation } from './rsl-scope';
import { RslCompletionProvider } from './rsl-completion';
import { RslScopeProvider } from './rsl-scope-provider';
import { RslLinker } from './rsl-linker';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type RslAddedServices = {
    references: {
        QualifiedNameProvider: QualifiedNameProvider
    },
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
 export type RslServices = LangiumServices & RslAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
 export const RslModule: Module<RslServices, PartialLangiumServices & RslAddedServices> = {
    references: {
        ScopeComputation: (services) => new RslScopeComputation(services),
        ScopeProvider: (services) => new RslScopeProvider(services),
        Linker: (services) => new RslLinker(services),
        QualifiedNameProvider: () => new QualifiedNameProvider()
    },
    lsp: {
       CompletionProvider: (services) => new RslCompletionProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createRslServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Rsl: RslServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        RslGeneratedSharedModule
    );
    const Rsl = inject(
        createDefaultModule({ shared }),
        RslGeneratedModule,
        RslModule
    );
    shared.ServiceRegistry.register(Rsl);
    // registerValidationChecks(Rsl);
    return { shared, Rsl };
}
