import ElkConstructor from 'elkjs/lib/elk.bundled';
import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    Module, PartialLangiumServices
} from 'langium';
import { AslGeneratedModule, AslGeneratedSharedModule } from './generated/module';
import { AslNameProvider } from './asl-naming';
import { AslScopeComputation } from './asl-scope';
import { AslCompletionProvider } from './asl-completion';
import { AslScopeProvider } from './asl-scope-provider';
import { AslLinker } from './asl-linker';
import { DefaultElementFilter, ElkFactory, ElkLayoutEngine, IElementFilter, ILayoutConfigurator } from 'sprotty-elk/lib/elk-layout';
import { LangiumSprottyServices, LangiumSprottySharedServices, SprottyDiagramServices, SprottySharedModule } from 'langium-sprotty';
import { AslDiagramGenerator } from './asl-diagram-generator';
import { AslLayoutConfigurator } from './asl-layout-config';
import { AslValidator } from './asl-validator';
// import { AslValidator, registerValidationChecks } from './asl-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type AslAddedServices = {
    layout: {
        ElkFactory: ElkFactory,
        ElementFilter: IElementFilter,
        LayoutConfigurator: ILayoutConfigurator
    }
     validation: {
         AslValidator: AslValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type AslServices =  LangiumSprottyServices & AslAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const AslModule: Module<AslServices, PartialLangiumServices & SprottyDiagramServices & AslAddedServices> = {
    references: {
        ScopeComputation: (services) => new AslScopeComputation(services),
        ScopeProvider: (services) => new AslScopeProvider(services),
        Linker: (services) => new AslLinker(services),
        NameProvider: () => new AslNameProvider(),
    },
    lsp: {
       CompletionProvider: (services) => new AslCompletionProvider(services)
    },
    diagram: {
        DiagramGenerator: services => new AslDiagramGenerator(services),
        ModelLayoutEngine: services => new ElkLayoutEngine(services.layout.ElkFactory, services.layout.ElementFilter, services.layout.LayoutConfigurator) as any
    },
    layout: {
        ElkFactory: () => () => new ElkConstructor({ algorithms: ['layered'] }),
        ElementFilter: () => new DefaultElementFilter,
        LayoutConfigurator: () => new AslLayoutConfigurator
    },
    validation: {
         AslValidator: () => new AslValidator()
     }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createAslServices(context: DefaultSharedModuleContext): {
    shared: LangiumSprottySharedServices,
    Asl: AslServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        AslGeneratedSharedModule,
        SprottySharedModule
    );
    const Asl = inject(
        createDefaultModule({ shared }),
        AslGeneratedModule,
        AslModule
    );
    shared.ServiceRegistry.register(Asl);
    //registerValidationChecks(Asl);
    return { shared, Asl };
}
